export const navLists = ["All Product", "Add Product"];
// subtitle: 'fast relieve for headache',
export const allproductLists = [
  {
    id: 1,
    name: "Emzor Paracetamol",
    category: "Pain Killers",
    brand: "Emzor",
    stock: 23,
    qtysold: 11,
    expired: 3,
    unitPrice: "₦3500",
    dateAdded: "23rd Jan, 2025",
    actions: "Actions",
  },
  {
    id: 2,
    name: "Ibuprofen Tablets",
    category: "Pain Killers",
    brand: "M&B",
    stock: 45,
    qtysold: 20,
    expired: 2,
    unitPrice: "₦1500",
    dateAdded: "5th Feb, 2025",
    actions: "Actions",
  },
  {
    id: 3,
    name: "Vitamin C 1000mg",
    category: "Supplements",
    brand: "Emzor",
    stock: 50,
    qtysold: 30,
    expired: 5,
    unitPrice: "₦500",
    dateAdded: "12th Mar, 2025",
    actions: "Actions",
  },
  {
    id: 4,
    name: "Cough Syrup",
    category: "Cold & Flu",
    brand: "Benylin",
    stock: 35,
    qtysold: 15,
    expired: 1,
    unitPrice: "₦2800",
    dateAdded: "18th Apr, 2025",
    actions: "Actions",
  },
  {
    id: 5,
    name: "Amoxicillin Capsules",
    category: "Antibiotics",
    brand: "GSK",
    stock: 60,
    qtysold: 40,
    expired: 0,
    unitPrice: "₦4500",
    dateAdded: "25th May, 2025",
    actions: "Actions",
  },
  {
    id: 6,
    name: "Diclofenac Gel",
    category: "Pain Relief",
    brand: "Novartis",
    stock: 20,
    qtysold: 10,
    expired: 0,
    unitPrice: "₦2200",
    dateAdded: "30th Jun, 2025",
    actions: "Actions",
  },
  {
    id: 7,
    name: "Insulin Injection",
    category: "Diabetes Care",
    brand: "Novo Nordisk",
    stock: 18,
    qtysold: 5,
    expired: 1,
    unitPrice: "₦7200",
    dateAdded: "10th Jul, 2025",
    actions: "Actions",
  },
  {
    id: 8,
    name: "Multivitamin Capsules",
    category: "Supplements",
    brand: "Wellman",
    stock: 40,
    qtysold: 22,
    expired: 2,
    unitPrice: "₦3500",
    dateAdded: "15th Aug, 2025",
    actions: "Actions",
  },
  {
    id: 9,
    name: "Cetrizine Tablets",
    category: "Allergy Relief",
    brand: "Zyrtec",
    stock: 25,
    qtysold: 18,
    expired: 0,
    unitPrice: "₦1300",
    dateAdded: "1st Sep, 2025",
    actions: "Actions",
  },
  {
    id: 10,
    name: "Chloroquine Tablets",
    category: "Malaria Treatment",
    brand: "Swipha",
    stock: 30,
    qtysold: 12,
    expired: 4,
    unitPrice: "₦2800",
    dateAdded: "20th Oct, 2025",
    actions: "Actions",
  },
  {
    id: 11,
    name: "Folic Acid Tablets",
    category: "Pregnancy Care",
    brand: "Emzor",
    stock: 70,
    qtysold: 35,
    expired: 3,
    unitPrice: "₦900",
    dateAdded: "11th Nov, 2025",
    actions: "Actions",
  },
  {
    id: 12,
    name: "Artemether Injection",
    category: "Malaria Treatment",
    brand: "Lonart",
    stock: 22,
    qtysold: 10,
    expired: 1,
    unitPrice: "₦3500",
    dateAdded: "28th Dec, 2025",
    actions: "Actions",
  },
  {
    id: 13,
    name: "Hydroxychloroquine",
    category: "Anti-inflammatory",
    brand: "Sanofi",
    stock: 27,
    qtysold: 9,
    expired: 0,
    unitPrice: "₦4800",
    dateAdded: "3rd Jan, 2026",
    actions: "Actions",
  },
  {
    id: 14,
    name: "Prednisolone Tablets",
    category: "Steroids",
    brand: "Pfizer",
    stock: 32,
    qtysold: 18,
    expired: 1,
    unitPrice: "₦3200",
    dateAdded: "14th Feb, 2026",
    actions: "Actions",
  },
  {
    id: 15,
    name: "Metformin Tablets",
    category: "Diabetes Care",
    brand: "Merck",
    stock: 40,
    qtysold: 25,
    expired: 2,
    unitPrice: "₦2500",
    dateAdded: "22nd Mar, 2026",
    actions: "Actions",
  },
  {
    id: 16,
    name: "Omeprazole Capsules",
    category: "Ulcer Treatment",
    brand: "Gaviscon",
    stock: 36,
    qtysold: 15,
    expired: 1,
    unitPrice: "₦2800",
    dateAdded: "5th Apr, 2026",
    actions: "Actions",
  },
];

export const allproductColumn = [
  { key: "id", label: "ID" },
  { key: "name", label: "Name" },
  { key: "category", label: "Category" },
  { key: "brand", label: "Brand" },
  { key: "stock", label: "Stock" },
  { key: "qtysold", label: "Quantity Sold" },
  { key: "expired", label: "Expired" },
  { key: "unitPrice", label: "Unit Price" },
  { key: "dateAdded", label: "Date Added" },
  { key: "actions", label: "Actions" },
];
