export const defaultTextColor = "text-amber-500";
export const oliveColorBg = "bg-white";
export const oliveColorText = "text-white";
export const oliveColorBorder = "border-b border-white";
export const oliveColor = "white";
export const darkblue = "#1377ce"; //dark blue
export const darkblueHover = "border-[#1377ce]"; //dark blue
export const darkblueText = "text-[#1377ce]"; //dark blue
export const darkOrange = "#ff610d"; // orange
export const darkOrangeText = "text-[#ff610d]"; // orange
export const darkGreen = "#1ec12c"; // green
export const darkGreenText = "text-[#1ec12c]"; // green
export const darkyellow = "#FDD603"; // yellow
export const darkyellowText = "text-[#FDD603]"; // yellow
export const darkred = "#b8201a"; // red
export const darkredText = "text-[#b8201a]"; // red
export const adminDefaultBgColor = "bg-[#efefef]";
export const lightBlueBgColor = "bg-[#cfe6f9]"; //
export const lightorangeBgColor = "bg-[#faddd6]"; //
export const lightgreenBgColor = "bg-[#d6edd6]"; //
export const lightyellowBgColor = "bg-[#fff7d5]"; //
export const lightredBgColor = "bg-[#ffcfc8]"; //

// export const adminDefaultBgColor = "#ffedc9";
// export const oliveColorBg = "bg-[#687451]";
// export const oliveColorText = "text-[#687451]";
// export const oliveColorBorder = "border-b border-[#687451]";
// export const oliveColor = "#687451";
// export const darkestBrown = "#3f3114";
// export const darkerBrown = "#4c2b08";
// export const lightestBrown = "#ab7843";
// export const normalBrown = "#6d3914";
// export const adminDefaultBgColor = "bg-[#ffedc9]";
