export const orderLists = [
  {
    orderId: "ORD001",
    customerName: "John Adewale",
    phone: "+2348101234567",
    email: "john.adewale@example.com",
    address: "12 Bode Thomas Street, Lagos",
    // items: [
    //   { name: "Paracetamol 500mg", quantity: 2, price: "₦500" },
    //   { name: "Vitamin C 1000mg", quantity: 1, price: "₦1,500" },
    // ],
    totalItems: 3,
    totalAmount: "₦2,500",
    status: "Delivered",
    paymentMethod: "Paystack",
    orderDate: "2024-03-28",
  },
  {
    orderId: "ORD002",
    customerName: "Chidinma Okonkwo",
    phone: "+2349023456789",
    email: "chidinma.okonkwo@example.com",
    address: "45 Awolowo Road, Abuja",
    // items: [
    //   { name: "Ibuprofen 400mg", quantity: 3, price: "₦800" },
    //   { name: "Amoxicillin 500mg", quantity: 1, price: "₦2,000" },
    // ],
    totalItems: 4,
    totalAmount: "₦4,400",
    status: "Processing",
    paymentMethod: "Bank Transfer",
    orderDate: "2024-03-27",
  },
  {
    orderId: "ORD003",
    customerName: "Emeka Nwosu",
    phone: "+2348067890123",
    email: "emeka.nwosu@example.com",
    address: "78 Aba Road, Port Harcourt",
    // items: [
    //   { name: "Cough Syrup", quantity: 1, price: "₦1,200" },
    //   { name: "Loratadine 10mg", quantity: 2, price: "₦700" },
    // ],
    totalItems: 3,
    totalAmount: "₦2,600",
    status: "Shipped",
    paymentMethod: "Cash on Delivery",
    orderDate: "2024-03-26",
  },
  {
    orderId: "ORD004",
    customerName: "Fatima Bello",
    phone: "+2348034567890",
    email: "fatima.bello@example.com",
    address: "32 Kano Road, Kano",
    // items: [
    //   { name: "Multivitamin Tablets", quantity: 1, price: "₦2,500" },
    //   { name: "Blood Tonic", quantity: 1, price: "₦1,800" },
    // ],
    totalItems: 2,
    totalAmount: "₦4,300",
    status: "Delivered",
    paymentMethod: "Paystack",
    orderDate: "2024-03-25",
  },
  {
    orderId: "ORD005",
    customerName: "Adewale Ojo",
    phone: "+2349012345678",
    email: "adewale.ojo@example.com",
    address: "14 Ikorodu Road, Lagos",
    // items: [
    //   { name: "Malaria Test Kit", quantity: 2, price: "₦1,000" },
    //   { name: "Artemether/Lumefantrine", quantity: 1, price: "₦3,500" },
    // ],
    totalItems: 3,
    totalAmount: "₦5,500",
    status: "Pending",
    paymentMethod: "USSD",
    orderDate: "2024-03-24",
  },
  {
    orderId: "ORD006",
    customerName: "Ngozi Chukwuma",
    phone: "+2348123456789",
    email: "ngozi.chukwuma@example.com",
    address: "99 Wetheral Road, Owerri",
    // items: [
    //   { name: "Antiseptic Solution", quantity: 1, price: "₦2,500" },
    //   { name: "Thermometer", quantity: 1, price: "₦5,000" },
    // ],
    totalItems: 2,
    totalAmount: "₦7,500",
    status: "Shipped",
    paymentMethod: "Paystack",
    orderDate: "2024-03-23",
  },
  {
    orderId: "ORD007",
    customerName: "David Eze",
    phone: "+2348076543210",
    email: "david.eze@example.com",
    address: "22 New Market Road, Enugu",
    // items: [
    //   { name: "Insulin Pen", quantity: 1, price: "₦12,000" },
    //   { name: "Syringes (Pack of 10)", quantity: 1, price: "₦3,000" },
    // ],
    totalItems: 2,
    totalAmount: "₦15,000",
    status: "Delivered",
    paymentMethod: "Debit Card",
    orderDate: "2024-03-22",
  },
  {
    orderId: "ORD008",
    customerName: "Kemi Alade",
    phone: "+2349098765432",
    email: "kemi.alade@example.com",
    address: "56 Surulere Road, Lagos",
    // items: [
    //   { name: "Nebulizer", quantity: 1, price: "₦18,000" },
    //   { name: "Salbutamol Inhaler", quantity: 1, price: "₦2,500" },
    // ],
    totalItems: 2,
    totalAmount: "₦20,500",
    status: "Processing",
    paymentMethod: "Paystack",
    orderDate: "2024-03-21",
  },
  {
    orderId: "ORD009",
    customerName: "Abdullahi Yusuf",
    phone: "+2348023456789",
    email: "abdullahi.yusuf@example.com",
    address: "10 Emir's Palace Road, Kaduna",
    // items: [
    //   { name: "Glucose Monitor", quantity: 1, price: "₦15,000" },
    //   { name: "Lancets (Pack of 50)", quantity: 1, price: "₦3,500" },
    // ],
    totalItems: 2,
    totalAmount: "₦18,500",
    status: "Pending",
    paymentMethod: "Cash on Delivery",
    orderDate: "2024-03-20",
  },
  {
    orderId: "ORD010",
    customerName: "Blessing Uchenna",
    phone: "+2348135678901",
    email: "blessing.uchenna@example.com",
    address: "7 Ibadan Expressway, Ibadan",
    // items: [{ name: "Blood Pressure Monitor", quantity: 1, price: "₦25,000" }],
    totalItems: 1,
    totalAmount: "₦25,000",
    status: "Shipped",
    paymentMethod: "Debit Card",
    orderDate: "2024-03-19",
  },
];

export const orderListsColumn = [
  { key: "orderId", label: "Order Id" },
  { key: "customerName", label: "Customer Name" },
  { key: "phone", label: "Phone" },
  { key: "email", label: "Email" },
  { key: "address", label: "Address" },
  { key: "totalItems", label: "Total Items" },
  { key: "totalAmount", label: "Total Amount" },
  { key: "status", label: "Status" },
  { key: "paymentMethod", label: "Payment Method" },
  { key: "orderDate", label: "Order Date" },
];

export const orderTabList = [
  "All Orders",
  "Active Orders",
  "Pending Orders",
  "Cancelled Orders",
];
