
export const alltransactionsList = [
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP001",
      shippingType: "Express",
      shippingStatus: "Pending",
      itemTitle: "Paracetamol Tablets",
      itemQty: "2",
      amount: "₦2,500",
      orderDate: "2024-04-01",
      customerName: "Adekunle Adebayo",
      paymentMethod: "Bank Transfer",
      textColor: "text-gray-700",
      textBgColor: "bg-gray-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP002",
      shippingType: "Standard",
      shippingStatus: "Delivered",
      itemTitle: "Cough Syrup",
      itemQty: "1",
      amount: "₦4,000",
      orderDate: "2024-03-29",
      customerName: "Chinwe Okafor",
      paymentMethod: "USSD Payment",
      textColor: "text-green-600",
      textBgColor: "bg-green-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP003",
      shippingType: "Express",
      shippingStatus: "Cancelled",
      itemTitle: "Vitamin C Tablets",
      itemQty: "3",
      amount: "₦3,200",
      orderDate: "2024-03-28",
      customerName: "Emeka Obi",
      paymentMethod: "POS Payment",
      textColor: "text-red-600",
      textBgColor: "bg-red-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP004",
      shippingType: "Standard",
      shippingStatus: "Pending",
      itemTitle: "Ibuprofen Capsules",
      itemQty: "1",
      amount: "₦1,500",
      orderDate: "2024-03-27",
      customerName: "Fatima Bello",
      paymentMethod: "Mobile Banking",
      textColor: "text-yellow-600",
      textBgColor: "bg-yellow-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP005",
      shippingType: "Express",
      shippingStatus: "Delivered",
      itemTitle: "Blood Pressure Monitor",
      itemQty: "2",
      amount: "₦25,000",
      orderDate: "2024-03-25",
      customerName: "Tolu Akinwale",
      paymentMethod: "Cash on Delivery",
      textColor: "text-blue-600",
      textBgColor: "bg-blue-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP006",
      shippingType: "Standard",
      shippingStatus: "Pending",
      itemTitle: "Insulin Injection",
      itemQty: "1",
      amount: "₦12,000",
      orderDate: "2024-03-24",
      customerName: "Ibrahim Mohammed",
      paymentMethod: "Bank Transfer",
      textColor: "text-orange-600",
      textBgColor: "bg-orange-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP007",
      shippingType: "Express",
      shippingStatus: "Delivered",
      itemTitle: "Multivitamins",
      itemQty: "1",
      amount: "₦8,000",
      orderDate: "2024-03-22",
      customerName: "Kemi Alabi",
      paymentMethod: "Debit Card",
      textColor: "text-gray-800",
      textBgColor: "bg-gray-200",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP008",
      shippingType: "Standard",
      shippingStatus: "Cancelled",
      itemTitle: "Malaria Drug",
      itemQty: "1",
      amount: "₦5,500",
      orderDate: "2024-03-20",
      customerName: "Uchenna Nwosu",
      paymentMethod: "POS Payment",
      textColor: "text-purple-600",
      textBgColor: "bg-purple-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP009",
      shippingType: "Express",
      shippingStatus: "Delivered",
      itemTitle: "Pain Relief Gel",
      itemQty: "1",
      amount: "₦3,000",
      orderDate: "2024-03-18",
      customerName: "Segun Afolabi",
      paymentMethod: "USSD Payment",
      textColor: "text-indigo-600",
      textBgColor: "bg-indigo-100",
    },
    {
      image: "https://via.placeholder.com/150",
      shippingId: "SHIP010",
      shippingType: "Standard",
      shippingStatus: "Pending",
      itemTitle: "Asthma Inhaler",
      itemQty: "1",
      amount: "₦18,000",
      orderDate: "2024-03-15",
      customerName: "Amaka Eze",
      paymentMethod: "Mobile Banking",
      textColor: "text-teal-600",
      textBgColor: "bg-teal-100",
    },
  ];
  
  